spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vddatabase?serverTimezone=GMT
      username: root
      password: Xiechengyang20030220