spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vddatabase?serverTimezone=GMT
      username: root
      password: Xiechengyang20030220
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

server:
  port: 8070

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false
      id-type: auto
